version: '3'
services:
  fastapi:
    build: web_app/
    ports:
      - "8000:8000"
    networks:
      - app-network
  celery:
    build: remote_worker/
    command: celery -A celery_app worker --loglevel=info
    networks:
      - app-network
    depends_on:
      - redis
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - app-network
  flower:
    image: mher/flower
    ports:
      - "5555:5555"
    command: celery --broker=redis://redis:6379/0 flower --port=5555
    networks:
      - app-network
    depends_on:
      - redis
networks:
  app-network:
    driver: bridge
